### ISSUE TITLE
HTTPS required now

### ISSUE THREAD

**Issue by markchang** [technoweenie/twitter-node#14]
As of Sep. 30, 2011, Twitter requires SSL for the streaming API.

https://dev.twitter.com/blog/streaming-api-turning-ssl-only-september-29th

I do now know enough about Node to make this happen. Sorry!

**Comment by masterkain** [comment]
I did a quick and dirty patch: https://github.com/masterkain/twitter-node/commit/ada86e241e61dd726b01ddf097800693b6bb30fa

**Comment by technoweenie** [comment]
@dustin10 just submitted an [(accepted) patch](https://github.com/technoweenie/twitter-node/pull/15).
