### ISSUE TITLE
Error: ECONNREFUSED, Connection refused

### ISSUE THREAD

**Issue by senior-php-developer** [technoweenie/twitter-node#16]
at Client._onConnect (net.js:601:18)

**Comment by caljrimmer** [comment]
I am having the same issue - it started happening a few days ago. It was fine for about a month before that.

# 

node.js:205
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: ECONNREFUSED, Connection refused
    at Socket._onConnect (net_legacy.js:606:18)
    at IOWatcher.onWritable [as callback](net_legacy.js:186:12)

**Comment by caljrimmer** [comment]
Actually I think the issue is to do with:

https://dev.twitter.com/blog/streaming-api-turning-ssl-only-september-29th

**Comment by senior-php-developer** [comment]
thanks, updated index.js and it works now
