### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by bonifaido** [technoweenie/twitter-node#23]
Hi,

what about future npm package updates? (the latest package is currently 230 days old, and is broken because of twitter stream has moved to ssl)

Cheers,
Nandor

**Comment by technoweenie** [comment]
This project is discontinued.  See the repo description.

**Comment by dustin10** [comment]
If you pull the repo directly instead of using npm it will work.

**Comment by bonifaido** [comment]
Is it possible to use a git repo behind a dependency in package.json dependencies?

**Comment by bonifaido** [comment]
```
'dependencies': {
    'twitter-node': 'git://github.com/technoweenie/twitter-node.git'
}
```
