### ISSUE TITLE
example throws errors

### ISSUE THREAD

**Issue by ptarjan** [technoweenie/twitter-node#3]
the .count() throws "Parameter count not allowed in role status". 

The first location throws "Bounding box is invalid: 122.75, 36.80, -121.75, 37.80.  The first pair must be the SW corner of the boxBounding box is invalid: 122.75, 36.80, -121.75, 37.80.  The first pair must be the SW corner of the box"

and leaving the .sample() gives me a weird 416.

**Comment by technoweenie** [comment]
Those are just examples of how to change various parameters in Twitter-node.  
- [count docs](http://apiwiki.twitter.com/Streaming-API-Documentation#QueryParameters)
- [location docs](http://apiwiki.twitter.com/Streaming-API-Documentation#locations)
- [sample docs](http://apiwiki.twitter.com/Streaming-API-Documentation#statuses/sample)

There was a typo in the location docs, (their docs added a line break after the first `-` before 122.75), but that was an error from Twitter, not my library.  Any valid lat/long pairs should work.
