### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by auxbuss** [technoweenie/twitter-node#8]
<pre>
$ sudo npm install twitter-node
npm info it worked if it ends with ok
npm info using npm@0.3.9
npm info using node@v0.5.0-pre
npm info fetch http://registry.npmjs.org/twitter-node/-/twitter-node-0.0.2.tgz
npm info calculating sha1 /usr/local/lib/node/.npm/.cache/twitter-node/0.0.2/package.tgz
npm info shasum 8d81570e4c18a4cf7b9d884224e8b6fada764a1b
npm info preinstall twitter-node@0.0.2
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.050s)
Waf: Entering directory `/usr/local/lib/node/.npm/twitter-node/0.0.2/package/vendor/node-base64/build'
[1/2] cxx: base64.cc -> build/default/base64_1.o
../base64.cc: In function ‘v8::Handle<v8::Value> base64_encode_binding(const v8::Arguments&)’:
../base64.cc:178: error: ‘class node::Buffer’ has no member named ‘data’
../base64.cc:178: error: ‘class node::Buffer’ has no member named ‘length’
../base64.cc: In function ‘v8::Handle<v8::Value> base64_decode_binding(const v8::Arguments&)’:
../base64.cc:199: error: ‘class node::Buffer’ has no member named ‘data’
../base64.cc:199: error: ‘class node::Buffer’ has no member named ‘length’
Waf: Leaving directory `/usr/local/lib/node/.npm/twitter-node/0.0.2/package/vendor/node-base64/build'
Build failed:  -> task failed (err #1): 
    {task: cxx base64.cc -> base64_1.o}
cp: cannot stat `build/default/base64.node': No such file or directory
npm info twitter-node@0.0.2 Failed to exec preinstall script
npm ERR! install failed Error: twitter-node@0.0.2 preinstall: `./build.sh`
npm ERR! install failed `sh "-c" "./build.sh"` failed with 1
npm ERR! install failed     at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/npm/0.3.9/package/lib/utils/exec.js:49:20)
npm ERR! install failed     at ChildProcess.emit (events.js:45:17)
npm ERR! install failed     at ChildProcess.onexit (child_process.js:171:12)
npm info install failed rollback
npm info uninstall [ 'twitter-node@0.0.2' ]
npm info preuninstall twitter-node@0.0.2
npm info uninstall twitter-node@0.0.2
npm info auto-deactive not symlink
npm info postuninstall twitter-node@0.0.2
npm info uninstall twitter-node@0.0.2 complete
npm info install failed rolled back
npm ERR! Error: twitter-node@0.0.2 preinstall: `./build.sh`
npm ERR! `sh "-c" "./build.sh"` failed with 1
npm ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node/.npm/npm/0.3.9/package/lib/utils/exec.js:49:20)
npm ERR!     at ChildProcess.emit (events.js:45:17)
npm ERR!     at ChildProcess.onexit (child_process.js:171:12)
npm ERR! 
npm ERR! Failed at the twitter-node@0.0.2 preinstall script.
npm ERR! This is most likely a problem with the twitter-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./build.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls twitter-node
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.35-25-generic
npm not ok
</pre>

**Comment by technoweenie** [comment]
This library needs to be completely rewritten for Node 0.4.  I think
it's trying to compile some base64 lib someone added to squeeze some
performance out of hashing passwords.  This was before Node buffers
had base64 support baked in.

Also, I think there's a good fork of this project on GitHub somewhere.
 I get occasional Twitter @mentions about it, but no pull requests, so
I'm not sure.

**Comment by auxbuss** [comment]
I found this, which worked for me:

http://stackoverflow.com/questions/4407531/twitter-node-failing-to-build-node-js-npm-install-twitter-node

So, just npm install from within the clone of this repo.

So your repo is fine, it's just the npm version that is out of date.
